services:
  - type: web
    name: my-calculator
    runtime: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build-client
    startCommand: cd server && npm run deploy
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
    autoDeploy: true
